### ISSUE TITLE
UI Refinement: Social Handle Integration, Centered Event Calendar Title, and Stylish Amount Tab Hover Effects

### ISSUE THREAD

**Issue by NaveenChandraAdhikari** [JiyaGupta-cs/mytwit#18]
This issue aims to refine specific elements in our application's user interface for a more polished and user-friendly experience. The proposed changes include integrating social handles for contact purposes, centering the title in the events calendar, and applying stylish hover effects to the amount tab options.
Changes Proposed
1. Social Handle Integration

1.1 Contact Information

Add social media handles to the contact section, providing users with additional channels for communication. This integration can enhance accessibility and improve our online presence.
2. Event Calendar Title Alignment
2.1 Centered Title

Ensure that the title in the events calendar is properly centered for optimal visual alignment. This adjustment contributes to a more balanced and aesthetically pleasing UI.

3.Stylish Hover Animation

Implement a stylish hover effect for the amount tab options (e.g., 500 rs, 100 rs, 500 rs). When users hover over these options, consider extending the UI or applying a subtle animation to enhance the interactive experience.

WANT TO CONTRIBUTE IN THIS PROJECT UNDER JWOC

**Comment by Hacxmr** [comment]
Hey ! @JiyaGupta-cs  I am interested in contributing to the enhancement of UI. Can you assign me this task under JWOC?

**Comment by KumariAnkita04** [comment]
Hey @JiyaGupta-cs I am interested to work on this please assign me under JWoC'24

**Comment by NaveenChandraAdhikari** [comment]
This issue aims to refine specific elements in our application's user interface for a more polished and user-friendly experience. The proposed changes include integrating social handles for contact purposes, centering the title in the events calendar, and applying stylish hover effects to the amount tab options.
Changes Proposed
1. Social Handle Integration

1.1 Contact Information

Add social media handles to the contact section, providing users with additional channels for communication. This integration can enhance accessibility and improve our online presence.
2. Event Calendar Title Alignment
2.1 Centered Title

Ensure that the title in the events calendar is properly centered for optimal visual alignment. This adjustment contributes to a more balanced and aesthetically pleasing UI.

3.Stylish Hover Animation

Implement a stylish hover effect for the amount tab options (e.g., 500 rs, 100 rs, 500 rs). When users hover over these options, consider extending the UI or applying a subtle animation to enhance the interactive experience.

WANT TO CONTRIBUTE IN THIS PROJECT UNDER JWOC

**Comment by JiyaGupta-cs** [comment]
@NaveenChandraAdhikari You can open a new separate issue for hover effects, I am closing this one
