### ISSUE TITLE
Typo Error in README.md file

### ISSUE THREAD

**Issue by Divyanshgarg-04** [JiyaGupta-cs/mytwit#24]
I have found the typo error in the Readme.md file.

<img width="626" alt="Screenshot 2024-01-13 203714" src="https://github.com/JiyaGupta-cs/mytwit/assets/120127517/74e1f366-7f31-44a5-83bf-7bd092e89f5c">

**Comment by Divyanshgarg-04** [comment]
@JiyaGupta-cs Please assign this to me.

**Comment by SGCODEX** [comment]
I would like to work on this issue under JWOC

**Comment by KumariAnkita04** [comment]
Hey @JiyaGupta-cs I am willing to work on this issue under JWOC'24

**Comment by JiyaGupta-cs** [comment]
It's already resolved
You can work on other issues.
