### ISSUE TITLE
[FIX]: The "What's happening?" and "enter img url tag" bar improvement.

### ISSUE THREAD

**Issue by Ashutosh104** [JiyaGupta-cs/mytwit#26]
The "What's happening?" and "enter img url tag" bar should be more attractive and stylish.

**Comment by JiyaGupta-cs** [comment]
Please add screenshots of how you are going to make it

**Comment by Ashutosh104** [comment]
Something like this maybe.
![Screenshot 2024-01-16 231745](https://github.com/JiyaGupta-cs/mytwit/assets/143163927/43bba492-a958-4841-8c6c-cd10aafac5aa)
