### ISSUE TITLE
[Feature}: Create a login page-JWOC'24

### ISSUE THREAD

**Issue by Smritigit1202** [JiyaGupta-cs/mytwit#27]
To create a login page for the website

**Comment by Smritigit1202** [comment]
Please assign me the issue

**Comment by Smritigit1202** [comment]
I am contributing under JWOC projects

**Comment by JiyaGupta-cs** [comment]
Go ahead @Smritigit1202

**Comment by Smritigit1202** [comment]
I have made a pull request , please tell If I have done correct so far
