### ISSUE TITLE
[Fix]:Unable to Identify Active Sidebar Navigation Item

### ISSUE THREAD

**Issue by Abidsyed25** [JiyaGupta-cs/mytwit#29]
***Description:***
In the sidebar navigation, I noticed that the active navigation item is not being highlighted when navigating to different pages. This makes it challenging for users to identify their current location within the application.

***Expected Behavior:***
The active sidebar navigation item should be visually highlighted to provide a clear indication of the current page.

**Comment by Abidsyed25** [comment]
I would like to work on that issue under JWOC

**Comment by Abidsyed25** [comment]
Assign this issue to me. I am ready with a Pull Request.

**Comment by JiyaGupta-cs** [comment]
@Abidsyed25  Please attach screenshots of the issue you are referring to

**Comment by Abidsyed25** [comment]
***previous***
![jwoc3](https://github.com/JiyaGupta-cs/mytwit/assets/116893970/b05ea1f4-bfa0-4d4c-b0e8-d6331a800e18)
***if updated***
![jwoc4](https://github.com/JiyaGupta-cs/mytwit/assets/116893970/d0a9fa10-3915-4db0-a16d-794692f1940c)

It would enhance the user interface if the current page nav item is highighted.

**Comment by JiyaGupta-cs** [comment]
@Abidsyed25  Go ahead and make sure you follow the contributing.md

**Comment by JiyaGupta-cs** [comment]
Good job @Abidsyed25
