### ISSUE TITLE
Verify Post Content is not Empty

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/mytwit#31]
Make sure the user has written some content before posting
He does not do a empty post
Make description compulsory

**Comment by tsunami03** [comment]
Please assign me this issue

**Comment by JiyaGupta-cs** [comment]
@tsunami03
Go ahead and make sure you follow the contributing.md

**Comment by amanswarnakar** [comment]
Hey @JiyaGupta-cs, please assign this issue to me under JWOC'24.
