### ISSUE TITLE
Upgrading the UI of job mela section 

### ISSUE THREAD

**Issue by MandeyMan** [JiyaGupta-cs/mytwit#35]
![Screenshot 2024-01-17 163335](https://github.com/JiyaGupta-cs/mytwit/assets/120216011/8c56b0f5-15e0-4079-859c-f9d1856ffb73)

into 

![Screenshot 2024-01-17 163626](https://github.com/JiyaGupta-cs/mytwit/assets/120216011/c7c7b1bc-2258-43c7-9f1f-ab60319a8851)

i will make this card better in terms of UI

please grant me this issue under JWOC 2024

**Comment by vishal2005025** [comment]
I have read the issue and go through the code , I am eagerly want to contribute to this issue.
please assign it to me under JWOC'2024

**Comment by JiyaGupta-cs** [comment]
@MandeyMan 
Please choose some other issues as the UI already looks fine
