### ISSUE TITLE
[FIX]: Attractive search bar.

### ISSUE THREAD

**Issue by Ashutosh104** [JiyaGupta-cs/mytwit#38]
The search bar should be more stylish and attractive.

**Comment by Shu12388y** [comment]
@Ashutosh104 can assign this issue to me under jwoc

**Comment by subh03** [comment]
i want to work on this under jwoc

**Comment by JiyaGupta-cs** [comment]
@Ashutosh104 Attach image how do you want it to be

**Comment by Ashutosh104** [comment]
https://github.com/JiyaGupta-cs/mytwit/assets/143163927/7df158c1-ba69-42d7-b0f3-81f3a02926fe

**Comment by JiyaGupta-cs** [comment]
Look for other major issues
