### ISSUE TITLE
# Issue: Half-Visible Comma on the Page

### ISSUE THREAD

**Issue by ramith-kulal** [JiyaGupta-cs/mytwit#39]
## Problem Description

There is an issue with a comma on the page, where it is only half-visible. This could impact the readability and aesthetics of the page.

## Expected Behavior

The commas should not be present on the page. It should be removed  to ensure a clean and correct rendering of the content.

## Screenshot
![Screenshot 2024-01-18 222530](https://github.com/JiyaGupta-cs/mytwit/assets/142984776/6bb194c4-7423-4a59-ab73-59a327be3362)

Would like to work on this.

**Working under JWoC'24**

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Assigning it to you
