### ISSUE TITLE
Search bar does not work on clicking.

### ISSUE THREAD

**Issue by amanswarnakar** [JiyaGupta-cs/mytwit#42]
Problem description: 
Currently when the search bar is clicked on the right part it doesn't get focused as the typing cursor does not appear.

Solution:
Make the search bar work correctly. Clicking on it should bring it on focus.

Problem Preview:

https://github.com/JiyaGupta-cs/mytwit/assets/80145855/33f31f2a-d4fd-48ae-903f-4138b38efe1f

**Comment by JiyaGupta-cs** [comment]
@amanswarnakar 
Instead make it functional and let the users search the post which are in the middle section

**Comment by amanswarnakar** [comment]
@JiyaGupta-cs sure will do that. Assign this issue to me under JWOC'24.
