### ISSUE TITLE
Feature Request - Add "Go to Top" Button

### ISSUE THREAD

**Issue by rahat2134** [JiyaGupta-cs/mytwit#47]
The current website lacks a "Go to Top" button, which can enhance user experience by allowing them to quickly navigate back to the top of the page. This feature is especially useful for pages with lengthy content, ensuring users can easily return to the start without manual scrolling.

Proposed Changes
Implement a "Go to Top" button that appears as users scroll down the page.
Position the button in a corner of the screen, maintaining visibility but not obstructing content.
Ensure smooth scrolling animation when users click the button.

Benefits
Improved user navigation by providing a convenient way to return to the top.
Enhances overall user experience, particularly on pages with extensive content.
Demonstrates a commitment to user-friendly design practices.
![image](https://github.com/JiyaGupta-cs/mytwit/assets/136263179/b31d503e-b3e9-438f-bab7-9a226908ec11)

**image is just an example.

**Comment by rahat2134** [comment]
@JiyaGupta-cs  assign this issue to me under jwoc.

**Comment by JiyaGupta-cs** [comment]
@rahat2134 Go for it

**Comment by rahat2134** [comment]
@JiyaGupta-cs thanks u so much.

**Comment by JiyaGupta-cs** [comment]
It's not that hard for that label
But you can look for other hard issues

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal go ahead
