### ISSUE TITLE
Feature Request: Text edit

### ISSUE THREAD

**Issue by TanushreeBorase** [JiyaGupta-cs/mytwit#50]
<img width="630" alt="image" src="https://github.com/JiyaGupta-cs/mytwit/assets/130696335/87e65c7b-b31b-4c6f-a6a5-e241d0d2d2b3">

Want to work on this issue under JWOC'24

 I would like to suggest that instaed of text like XX , can we put information like:
UDID Card or Unique Disability Identity card is an initiative by Government of India with a view of creating a National Database for PwDs, and to issue a Unique Disability Identity Card  to each person with disabilities. 
As of now, AADHAAR is not mandatory for issuance of UDID card.
or 
Javelin thrower Sumit Antil and archer Sheetal Devi won the prestigious Best Male and Best Female Athlete awards at the first Divyang Sports Awards.

Sheetal Devi had won two gold and one silver in the Asian Para Games held in Hangzhou, China.
He has been chosen the Best Young Athlete of the Year 2023.

Sumit Antil on gold medals in the men's javelin throw F64 category at the 2020 Summer Paralympics and the 2023 World Para Athletics Championships.

He holds the current world record with a throw of 73.29 meters at the 2022 Asian Para Games in Hangzhou.

**Comment by JiyaGupta-cs** [comment]
@TanushreeBorase 
I have not put the text like that
If any of the contributors visit that page then he writes something there like this
