### ISSUE TITLE
TOO Many Issue

### ISSUE THREAD

**Issue by tushargupta1504** [JiyaGupta-cs/mytwit#58]
1.
1. There is not any button actually working like post the post button is not working .
2. also in the post the spam filter and the words which are to be blokced automatically are not there .
3.  Like button not working and no other bn.
4. No login page is there in this website so add a login or sign up page if does not vant to add atleast ask the name or profile of the user to, to make it actually social. 
Assign all this to me I

**Comment by JiyaGupta-cs** [comment]
@tushargupta1504 Please take up one issue at a time and make sure it is not duplicate
Also mention your workflow

**Comment by JiyaGupta-cs** [comment]
@tushargupta1504 

> @tushargupta1504 Please take up one issue at a time and make sure it is not duplicate Also mention your workflow

If you want to work then open new separate issues, I am closing this one
