### ISSUE TITLE
enhanching side bar elements

### ISSUE THREAD

**Issue by sristy17** [JiyaGupta-cs/mytwit#68]
add more effects, to buttons and elements..

if approve please assign under jwoc.

**Comment by JiyaGupta-cs** [comment]
@sristy17 Elaborate you issue description and clearly mention to which button you want to add which effect

**Comment by sristy17** [comment]
i was trying to add more hover effects on the the side bar elements like explore, event,etc and also to the buttons like post.

**Comment by sristy17** [comment]
Can you please check the current pr. I fixed the bug

**Comment by JiyaGupta-cs** [comment]
@sristy17 Dear, I have closed it you can check that out
