### ISSUE TITLE
Add customised scrollbar to the website

### ISSUE THREAD

**Issue by Sneha123-zudo** [JiyaGupta-cs/mytwit#69]
Please assign me this issue under JWOC'24

**Comment by JiyaGupta-cs** [comment]
@Sneha123-zudo Assigning you

**Comment by ramith-kulal** [comment]
is this still open? , if so i would like to work under jwoc

**Comment by sristy17** [comment]
Can you assign me with this?

**Comment by JiyaGupta-cs** [comment]
@ramith-kulal Go ahead
