### ISSUE TITLE
Add GitHub Issue and PR Template

### ISSUE THREAD

**Issue by JiyaGupta-cs** [JiyaGupta-cs/mytwit#70]
# Description

Add GitHub Issue and PR Template so that new comers can make issues and PR easily

**Comment by Prithwi32** [comment]
@JiyaGupta-cs  I would like to work on this issue under Jwoc

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 go ahead

**Comment by Prithwi32** [comment]
Thank you

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 It's not working
Try making a new issue 
You can see there

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 
https://github.com/JiyaGupta-cs/ShopNex/issues/69
Take reference from this

**Comment by Prithwi32** [comment]
> @Prithwi32 [JiyaGupta-cs/ShopNex#69](https://github.com/JiyaGupta-cs/ShopNex/issues/69) Take reference from this

@JiyaGupta-cs  Hello..may I know what changes i should made now?

**Comment by JiyaGupta-cs** [comment]
Your code is not working @Prithwi32 
When I merged it and created a new issue I couldn't see the template
That's why I opened the issue again and reverted the merge

**Comment by JiyaGupta-cs** [comment]
@Prithwi32 
The reason is that the files which you added were all inside GitHub workflows folder
They should come outside it

**Comment by Prithwi32** [comment]
okay tq i will change it
